unit iLibrary_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROClasses, uROClient, uROTypes, uROClientIntf,
  {Used RODLs:} DataAbstract4_Intf;

const
  { Library ID }
  LibraryUID = '{41BE3CB1-6552-424C-AF43-5036241712D7}';
  TargetNamespace = '';

  { Service Interface ID's }
  IiService_IID : TGUID = '{71A7278C-9ACF-4EA0-ACD3-8DC13C7EEFBD}';

  { Event ID's }

type
  { Forward declarations }
  IiService = interface;




  { IiService }
  IiService = interface(IDataAbstractService)
    ['{71A7278C-9ACF-4EA0-ACD3-8DC13C7EEFBD}']
  end;

  { CoiService }
  CoiService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IiService;
  end;

  { TiService_Proxy }
  TiService_Proxy = class(TDataAbstractService_Proxy, IiService)
  protected
    function __GetInterfaceName:string; override;

  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uRORes;

{ CoiService }

class function CoiService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IiService;
begin
  result := TiService_Proxy.Create(aMessage, aTransportChannel);
end;

function TiService_Proxy.__GetInterfaceName:string;
begin
  result := 'iService';
end;

initialization
  RegisterProxyClass(IiService_IID, TiService_Proxy);


finalization
  UnregisterProxyClass(IiService_IID);

end.
