--创建表空间 MyErp
/*
初始信息
数据库部分: 全局 orcl   orcl/orcl;[用户名与口令];
命名空间: myerp
用户名: sys/sys[超级用户]  developer/developer[开发人员];
*/


CREATE SMALLFILE TABLESPACE "MYERP" DATAFILE 'C:\ORACLE\PRODUCT\10.2.0\ORADATA\ORCL\myerp' SIZE 100M AUTOEXTEND ON NEXT 1000K MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--创建用户名 DEVELOPER / DEVELOPER
CREATE USER "DEVELOPER" PROFILE "DEFAULT" IDENTIFIED BY "developer" DEFAULT TABLESPACE "MYERP" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
--分配角色权限
GRANT "CONNECT" TO "DEVELOPER";
GRANT "DBA" TO "DEVELOPER";
GRANT "RESOURCE" TO "DEVELOPER";

--登陆 DEVELOPER
connect developer/developer@orcl;
--超级用户方式登陆
--connect sys/sys@orcl as sysdba;
