unit erpLibrary_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf,
  {Used RODLs:} DataAbstract4_Intf;

const
  { Library ID }
  LibraryUID = '{7E7F8FB9-0456-44ED-9B0D-88865B268F2D}';
  TargetNamespace = '';

  { Service Interface ID's }
  IerpService_IID : TGUID = '{6A2F3D2B-59AB-4B1C-B765-57F15C1C2CB9}';

  { Event ID's }

type
  { Forward declarations }
  IerpService = interface;





  { Enumerateds }

  { IerpService }
  IerpService = interface(IDataAbstractService)
    ['{6A2F3D2B-59AB-4B1C-B765-57F15C1C2CB9}']
  end;

  { CoerpService }
  CoerpService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IerpService;
  end;

  { TerpService_Proxy }
  TerpService_Proxy = class(TDataAbstractService_Proxy, IerpService)
  protected
    function __GetInterfaceName:string; override;

  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoerpService }

class function CoerpService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IerpService;
begin
  result := TerpService_Proxy.Create(aMessage, aTransportChannel);
end;

function TerpService_Proxy.__GetInterfaceName:string;
begin
  result := 'erpService';
end;

initialization
  RegisterProxyClass(IerpService_IID, TerpService_Proxy);


finalization
  UnregisterProxyClass(IerpService_IID);

end.
